import type { Metadata } from "next";
import "./globals.css";
import FreePdf from "./components/FreePdf";

export const metadata: Metadata = {
  title: "Allan Drapper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <FreePdf />
      </body>
    </html>
  );
}
